Neha/App/urls.py
from django.conf.urls import url
from . import views
app_name = 'App'

urlpatterns =[
    url(r'home/',views.hello,name = 'hello'),
    url(r'alluser/',views.alluser,name = 'alluser'),
    url(r'^(?P<parameter>[0-9]+)/$',views.showuser,name = 'showuser'),
    url(r'creditsto/',views.creditsto,name = 'creditsto'),
    url(r'transfer/(?P<parameter2>[0-9]+)/$',views.transfer,name = 'transfer'),
    url(r'last/',views.last,name = 'last'),
    url(r'TransferDetails/',views.TransferDetails,name = 'tDetails'),
    url(r'Cancel/',views.Cancel,name = 'Cancel'),
    url(r'showuser2/(?P<parameter3>[0-9]+)/$',views.showuser2,name = 'showuser2'),
    ]

Neha/Neha/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('admin/', admin.site.urls),

    #path('add/',include('App.urls')),
    path('hello/',include('App.urls')),
]

Neha/App/models.py
from django.db import models

class User(models.Model):
    Name = models.CharField(max_length = 30)
    Email = models.CharField(max_length = 50)
    credit = models.CharField(max_length = 20)
    contact_no = models.CharField(max_length = 20)
    city = models.CharField(max_length = 20)
    def __str__(self):
        return self.Name+'    '+self.Email+'  '+self.credit
class Transfer(models.Model):
    from_user_name = models.CharField(max_length = 30)
    to_user_name = models.CharField(max_length = 50)
    transfer_credit = models.CharField(max_length = 20)
    created_at = models.DateTimeField(auto_now_add = True)
    def __str__(self):
        return self.from_user_name+'    '+self.to_user_name+'  '+self.transfer_credit
    
    
    


# Create your models here.

Neha/App/views.py
from django.shortcuts import render
from .models import User
from django.template import loader
from django.http import HttpResponse
from .models import Transfer
#fromuser = 0
#touser = 0
def showuser(request,parameter):
    u1 = User.objects.get(id = parameter)
    t1 = Transfer.objects.filter(from_user_name = u1.Name)
    n1 = t1.count()
    t2 = Transfer(from_user_name = u1.Name)
    t2.save()
    t3 = Transfer.objects.filter(to_user_name = u1.Name)
    n2 = t3.count()
    if(n1>0):
        x = t1[n1-1]
        if(n2>0):
            y = t3[n2-1]
            context = {'u1':u1,'x':x,'y':y}
        else:
            y = 0
            context = {'u1':u1,'x':x,'y':y}
    elif(n2>0):
        x = 0
        y = t3[n2-1]
        context = {'u1':u1,'x':x,'y':y}
    if(n1 == 0 and n2 == 0):
        x = 0
        y = 0
        context = {'u1':u1,'x':x,'y':y}
    
    
    template = loader.get_template('html_ki_file/showuser.html')
     
    return HttpResponse(template.render(context,request))
    #return HttpResponse(" id:- "+str(u1.id)+"<br> "+"Name:- "+u1.Name+"<br>"+"E-mail:- "+u1.Email+"<br> "+"Credit:- "+u1.credit)
def hello(request):
    u1 = User.objects.all()
    template = loader.get_template('html_ki_file/hello.html')
    context = {'u1':u1} 
    return HttpResponse(template.render(context,request))
def alluser(request):
    u1 = User.objects.all()
    template = loader.get_template('html_ki_file/alluser.html')
    context = {'u1':u1} 
    return HttpResponse(template.render(context,request))
def creditsto(request):
    u1 = User.objects.all()
    template = loader.get_template('html_ki_file/creditsto.html')
    context = {'u1':u1} 
    return HttpResponse(template.render(context,request))
def transfer(request,parameter2):
    u1 = User.objects.get(id = parameter2)
    
    template = loader.get_template('html_ki_file/transfer.html')
    context = {'u1':u1} 
    #return HttpResponse("enter the credit number")
    return HttpResponse(template.render(context,request))
def last(request):
    t2 = Transfer.objects.last()
    u2 = User.objects.get(Name = t2.from_user_name)
    credit = u2.credit
    if(int(credit) < int(request.POST['text1'])):
        template1 = loader.get_template('html_ki_file/transfer.html')
        context = {'credit':credit}
        template2 = loader.get_template('html_ki_file/transfer2.html')
        return HttpResponse(template2.render(context,request)+template1.render(context,request))
    else:
        t1 = Transfer.objects.last()
        t1.transfer_credit = request.POST['text1']
        t1.save()
        t1 = Transfer.objects.last()
        u_from = User.objects.get(Name = t1.from_user_name)
        value1 = int(u_from.credit) - int(t1.transfer_credit)
        u_from.credit = str(value1)
        u_from.save()
        u_from = User.objects.get(Name = t1.from_user_name)
        u_to = User.objects.get(Name = t1.to_user_name)
        value2 = int(u_to.credit) + int(t1.transfer_credit)
        u_to.credit = str(value2)
        u_to.save()
        u_to = User.objects.get(Name = t1.to_user_name)
        template = loader.get_template('html_ki_file/last.html')
        context = {'t1':t1}
        return HttpResponse(template.render(context,request))
    
    #return HttpResponse("transfered succesfully"+t1.from_user_name+" "+t1.to_user_name+" "+t1.transfer_credit+" "+u_from.Name+" "+u_from.credit+" "+u_to.Name+" "+u_to.credit)
def TransferDetails(request):
    t1 = Transfer.objects.all()
    template = loader.get_template('html_ki_file/TransferDetails.html')
    context = {'t1':t1} 
    return HttpResponse(template.render(context,request))
def Cancel(request):
    t1 = Transfer.objects.last()
    t2 = Transfer.objects.all()
    n1 = t2.count()
    if(n1>0):
        t1.delete()
    u1 = User.objects.all()
    template = loader.get_template('html_ki_file/alluser.html')
    context = {'u1':u1} 
    return HttpResponse(template.render(context,request))
def showuser2(request,parameter3):
    u1 = User.objects.get(id = parameter3)
    p = parameter3
    t1 = Transfer.objects.filter(from_user_name = u1.Name)
    n1 = t1.count()
    t2 = Transfer.objects.last()
    t2.to_user_name = u1.Name
    t2.save()
    t3 = Transfer.objects.filter(to_user_name = u1.Name)
    n2 = t3.count()
    if(n1>0):
        x = t1[n1-1]
        if(n2>1):
            y = t3[n2-2]
            context = {'u1':u1,'x':x,'y':y,'p':p}
        else:
            y = 0
            context = {'u1':u1,'x':x,'y':y,'p':p}
    elif(n2>1):
        x = 0
        y = t3[n2-2]
        context = {'u1':u1,'x':x,'y':y,'p':p}
    if(n1 == 0 and n2 == 1):
        x = 0
        y = 0
        context = {'u1':u1,'x':x,'y':y,'p':p}
    template = loader.get_template('html_ki_file/showuser2.html')
     
    return HttpResponse(template.render(context,request))
    
    
                
    
    

# 
    
                
    
    

# Create your views here.

Neha/App/templates/html_ki_file/TransferDetails.html
{% load staticfiles %}
<link rel = "stylesheet" type="text/css" href = "{% static 'style2.css' %}">
{% load staticfiles %}
<link rel = "stylesheet" type="text/css" href = "{% static 'style.css' %}">
<html lang = "en">
<head>
<meta charset = "UTF-8">
<title></title><style>
tr {
color:white;
font-size : 30px;
}
</style>
<script>
function func(){
window.location = "hello/home/"
}
</script>
</head>
<body>
<div class = "st"><i>Transfer credits here:-</i></div>
<table>
<tr><th>From</th><th>To</th><th>Credit-Transfered</th><th>Transfered at:-</th>
</tr>
{% for i in t1 %}
<tr>
<td>
&nbsp;&nbsp;&nbsp;&nbsp;{{i.from_user_name}}&nbsp;&nbsp;&nbsp;&nbsp;</td>
<td>
&nbsp;&nbsp;&nbsp;&nbsp;{{i.to_user_name}}&nbsp;&nbsp;&nbsp;&nbsp;</td>
<td>
&nbsp;&nbsp;&nbsp;&nbsp;{{i.transfer_credit}}</td>&nbsp;&nbsp;&nbsp;&nbsp;
<td>
&nbsp;&nbsp;&nbsp;&nbsp;{{i.created_at}}&nbsp;&nbsp;&nbsp;&nbsp;</td>
</tr>
{% endfor %}
</table>
<button onclick = "func();">Home-Page</button>
</body>

Neha/App/templates/html_ki_file/adding.html
<html lang = "en">
<head>
<meta charset = "UTF-8">
<title></title>
</head>
<body>
hello lets add elemnts
</body>
</html>

Neha/App/templates/html_ki_file/alluser.html
{% load staticfiles %}
<link rel = "stylesheet" type="text/css" href = "{% static 'style2.css' %}">
{% load staticfiles %}
<link rel = "stylesheet" type="text/css" href = "{% static 'style.css' %}">
<html lang = "en">
<head>
<meta charset = "UTF-8">
<title></title>
<style>
a:hover{

color:green;
}
tr:hover td {
background-color:grey;
color:white;
}
tr{
color:white;
font-size:30px;
}

</style>
<script type = 'text/javascript'>
window.onload = function(){
var table1 = document.getElementById("table1"),rIndex,
rows = document.getElementsByTagName("tr");
for(var i=1;i< rows.length;i++)
{
table1.rows[i].onclick = function()
{
rIndex = this.rowIndex;
window.location = "/hello/"+rIndex

};
}} 
</script>
</head>
<body>
<div class = "st"><font size = "10"><i>Transfer Credits here :- </i></font></div>
<div style = "margin-top:40px;color:white;font-size:30px;">Transfer credit from:-<br><br>
<table id = "table1" border = "1" cellspacing = "0">
<tbody style = "cursor:pointer">
<tr  style = "color:black;" bgcolor = "pink">
<th>Name</th>
<th>E-mail</th>
<th>Current-credit</th></tr>

{% for i in u1 %}
<tr class = "rowhighlight" >
<td>&nbsp;&nbsp;&nbsp;&nbsp;{{i.Name}}&nbsp;&nbsp;&nbsp;&nbsp;</td>
<td>&nbsp;&nbsp;&nbsp;&nbsp;{{i.Email}}&nbsp;&nbsp;&nbsp;&nbsp;</td>
<td>&nbsp;&nbsp;&nbsp;&nbsp;{{i.credit}}&nbsp;&nbsp;&nbsp;&nbsp;</td>
</tr>
{% endfor %}
</tbody>
</table>
</div>
<p align = "left"><a href = "{% url 'App:hello' %}"><font size = "5">Go-back</a>
</body>
</html>

Neha/App/templates/html_ki_file/creditsto.html
{% load staticfiles %}
<link rel = "stylesheet" type="text/css" href = "{% static 'style2.css' %}">
{% load staticfiles %}
<link rel = "stylesheet" type="text/css" href = "{% static 'style.css' %}">
<html lang = "en">
<head>
<meta charset = "UTF-8">
<title></title>
</head>
<script type = 'text/javascript'>
window.onload = function(){
var table1 = document.getElementById("table1"),rIndex,
rows = document.getElementsByTagName("tr");
for(var i=1;i< rows.length;i++)
{
table1.rows[i].onclick = function()
{
rIndex = this.rowIndex;

window.location = "/hello/showuser2/"+rIndex

};
function func()
{
window.location = "{% url 'App:Cancel' %}"
}
}}
</script>
<style>
tr:hover td{
background-color:grey;

}
tr{
color:white;
font-size:30px;
}
</style>
</head>
<body>
<div class = "st"><i>Transfer Credits here :- </i></div>
<div style = "margin-top:40px;font-size:30px;color:white;">Transfer credit to:-<br><br>
<table id = "table1" border = "1" cellspacing = "0" cellpadding = "0">
<tbody style = "cursor:pointer">
<tr style = "color:white;" bgcolor = "pink">
<th>Name</th>
<th>E-mail</th>
<th>Current-credit</th></tr>

{% for i in u1 %}
<tr >

<td>&nbsp;&nbsp;&nbsp;&nbsp;{{i.Name}}&nbsp;&nbsp;&nbsp;&nbsp;</td>
<td>&nbsp;&nbsp;&nbsp;&nbsp;{{i.Email}}&nbsp;&nbsp;&nbsp;&nbsp;</td>
<td>&nbsp;&nbsp;&nbsp;&nbsp;{{i.credit}}&nbsp;&nbsp;&nbsp;&nbsp;</td>
</tr>
{% endfor %}
</tbody>
</table>
</div>
<br><br>
<button onclick = "func();" style = "float:right;">Cancel</button><br><br>
</body>
</html>

Neha/App/templates/html_ki_file/hello.html
{% load staticfiles %}
<link rel = "stylesheet" type="text/css" href = "{% static 'style.css' %}">
{% load staticfiles %}
<link rel = "stylesheet" type="text/css" href = "{% static 'style2.css' %}">
<html lang = "en">
<head>
<meta charset = "UTF-8">
<title></title>

<script>
function view()
{
window.location = "{% url 'App:alluser' %}"

}
</script>

</head>
<body >
<div class = "st"><i>Transfer Credits here :- </i></font></div>
<center><div style = "color:white;margin-top:140px;text-align:center;"><font size = "10">to view all user press this
<br><br><button style = "color:blue;" onclick = "view();"><font size = "7">View all users</button></div>
</body>
</html>

Neha/App/templates/html_ki_file/last.html
{% load staticfiles %}
<link rel = "stylesheet" type="text/css" href = "{% static 'style2.css' %}">
{% load staticfiles %}
<link rel = "stylesheet" type="text/css" href = "{% static 'style.css' %}">
<html lang = "en">
<head>
<meta charset = "UTF-8">
<title></title>
<script>
function func()
{
window.location = "/hello/TransferDetails"
}
function func2()
{
window.location = "/hello/home"
}
</script>
</head>
<body>
<div class = "st"><i>Transfere credits here:-</i></div>
<p style = "color:white;text-align:center;margin:140px"><font size = "7">
Transferred succesfully</p>


<button onclick = "func();"style = "float:right;">TransferDetails</button>
<button onclick = "func2();" style = "float:left;">Home-page</button>

</body>

Neha/App/templates/html_ki_file/showuser.html
{% load staticfiles %}
<link rel = "stylesheet" type="text/css" href = "{% static 'style2.css' %}">
{% load staticfiles %}
<link rel = "stylesheet" type="text/css" href = "{% static 'style.css' %}">
<html lang = "en">
<head>
<meta charset = "UTF-8">
<title></title>
<script>
function func(){
window.location = "{% url 'App:creditsto' %}"
};
function func2()
{
window.location = "{% url 'App:Cancel' %}"
}
</script>
<style>
tr{
color:white;
font-size:30px;
}
</style>
</head>
<body>
<div class = "st"><i>Transfer Credits here:-
</i></div>
<div style = "margin-top:40px;font-size:30px;color:white;">
<table>
<td>Name:-</td>
<td>{{u1.Name}}</td></tr>
<tr>
<td>E-mail:-</td>
<td>{{u1.Email}}</td></tr>
<tr>
<td>Current-credits:-</td>
<td>{{u1.credit}}</td></tr>
<tr>
<td>Contact-no:-</td>
<td>{{u1.contact_no}}</td></tr>
<tr>
<td>City:-</td>
<td>{{u1.city}}</td></tr>
</table>
{% if x != 0 %}
<p style = "color:purple">Last Transaction:-</p>
<table>


<tr>
<td>To:-</td>
<td>{{x.to_user_name}}</td>
</tr>
<tr>
<td>Transfered credit:-</td>
<td>{{x.transfer_credit}}</td>
</tr>

</table>
{% endif %}
{% if y != 0 %}
<p style = "color:purple">Last Transaction(credit gain:-):-</p>
<table>


<tr>
<td>From:-</td>
<td>{{y.from_user_name}}</td>
</tr>
<tr>
<td>credit gain:-</td>
<td>{{y.transfer_credit}}</td>
</tr>

</table>
{% endif %}
<button onclick = "func();" style = "float:right;">Transfer Credits to </button>

<button onclick = "func2();" style = "float:left;">Cancel</button>
</body>
</html>

Neha/App/templates/html_ki_file/showuser2.html
{% load staticfiles %}
<link rel = "stylesheet" type="text/css" href = "{% static 'style2.css' %}">
{% load staticfiles %}
<link rel = "stylesheet" type="text/css" href = "{% static 'style.css' %}">
<html lang = "en">
<head>
<meta charset = "UTF-8">
<title></title>
<script>

function func2()
{
window.location = "{% url 'App:Cancel' %}"
}
</script>
<style>
tr{
color:white;
font-size:30px;
}
</style>
</head>
<body>
<div class = "st"><i>Transfer Credits here:-
</i></div>
<div style = "margin-top:40px;font-size:30px;color:white;">
<table>
<td>Name:-</td>
<td>{{u1.Name}}</td></tr>
<tr>
<td>E-mail:-</td>
<td>{{u1.Email}}</td></tr>
<tr>
<td>Current-credits:-</td>
<td>{{u1.credit}}</td></tr>
<tr>
<td>Contact-no:-</td>
<td>{{u1.contact_no}}</td></tr>
<tr>
<td>City:-</td>
<td>{{u1.city}}</td></tr>
</table>
{% if x != 0 %}
<p style = "color:purple">Last Transaction:-</p>
<table>


<tr>
<td>To:-</td>
<td>{{x.to_user_name}}</td>
</tr>
<tr>
<td>Transfered credit:-</td>
<td>{{x.transfer_credit}}</td>
</tr>

</table>
{% endif %}
{% if y != 0 %}
<p style = "color:purple">Last Transaction(credit gain:-):-</p>
<table>


<tr>
<td>From:-</td>
<td>{{y.from_user_name}}</td>
</tr>
<tr>
<td>credit gain:-</td>
<td>{{y.transfer_credit}}</td>
</tr>

</table>
{% endif %}
<form action = "{% url  'App:transfer' p %}" method = "post">
{% csrf_token %}
<input type = "submit" style = "float:right;" value = "Transfer"></input>

</form>

<button onclick = "func2();" style = "float:left;">Cancel</button>
</body>
</html>

Neha/App/templates/html_ki_file/transfer.html
{% load staticfiles %}
<link rel = "stylesheet" type="text/css" href = "{% static 'style2.css' %}">
{% load staticfiles %}
<link rel = "stylesheet" type="text/css" href = "{% static 'style.css' %}">
<html lang = "en">
<head>
<meta charset = "UTF-8">
<title></title>
<script>
function validate()
{
if(document.myform.text1.value == "")
{
alert("enter credit points");
document.myform.text1.focus();
return false;
}
if(document.myform.text1.value < 0)
{
alert("enter positive credit points");
document.myform.text1.focus();
return false;
}

return true;
}
</script>
</head>
<body>
<div class = "st"><i>Transfer credits here:-</i><div>
<div style = "margin-top:140px;text-align;center">
<form action = "{% url 'App:last' %}" method = "Post" name = "myform" onsubmit = "return(validate());">
{% csrf_token %}
<p style = "color:white;font-size:30px;">enter the credit points which you want to transfer:-<br></p>
<input type = "text" name = "text1"></input><br>
<br><input type = "submit" value = "Transfer"></input>
</form>
</body>

Neha/App/templates/html_ki_file/transfer2.html
<html lang = "en">
<head>
<meta charset = "UTF-8">
<title></title>
<style>
body {
color:red;
font-size:30px;
}
</style>
</head>
<body>
Not sufficient credit to transfer!

</body>